### ISSUE TITLE
SQL File and Connection??

### ISSUE THREAD

**Issue by yusufusta** [marb61a/Vidztube#1]
Where is sql file and config file? I cant install script. 

`Fatal error: Uncaught ArgumentCountError: PDO::__construct() expects at least 1 parameter, 0 given in /home/quiec/www/includes/config.php:10 Stack trace: #0 /home/quiec/www/includes/config.php(10): PDO->__construct() #1 /home/quiec/www/includes/header.php(2): require_once('/home/quiec/www...') #2 /home/quiec/www/index.php(1): require_once('/home/quiec/www...') #3 {main} thrown in /home/quiec/www/includes/config.php on line 10`

**Comment by marb61a** [comment]
Hi  H. Yusuf Usta,
Apologies for the files not being on the repo, I left them out at the time
as
I was experimenting using C9.io as a dev platform. I have added in missing
config
info which will help with setting up the connection. I cannot access the
sql file at the moment
due to C9 freezing workspaces so I will have to wait until they finish
archiving the workspace
and then look for the sql file which I will add ASAP. Again apologies for
the missing info, I
hadn't thought anybody would use the files as it was a learning project.

Regards
Martin

**Comment by yusufusta** [comment]
okey! i can understand. your script is very good, should be some features to be better. thanks.
